version: 3.8.5.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input